objects/Position_approval_matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Position_approval_matrices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Position_approval_matrices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Position_approval_matrices2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position approval matrix</label>
    <nameField>
        <displayFormat>RoutingID-{000}</displayFormat>
        <label>Position approval matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Position approval matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vacancy__c.object
<CustomObject>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacancies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vacancies2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PositionApproval.cls
public class PositionApproval {
             
             
              static final Map<String,Position_Approval_Matrix__c> APPROVAL_MAP_CONST;
             
              static {
                             APPROVAL_MAP_CONST = getPositionApprovalMap();
              }
             
              private static Map<String,Position_Approval_Matrix__c> getPositionApprovalMap(){
                             // build a Map from Department --> Approval Matrix record
                             Map<String,Position_Approval_Matrix__c> results = new Map<String,Position_Approval_Matrix__c>();
                             List<Position_Approval_Matrix__c> records = [select id,name, Department__c,approver1__c,approver2__c,approver3__c from Position_Approval_Matrix__c];
                             for(Position_Approval_Matrix__c record : records){
                                           if (!results.containsKey(record.Department__c))
                                           {
                                            results.put(record.Department__c, record);
 

                                            }
                             }
                             return results;
              }
             
              public static void setPositionApprovers(Vacancy__c[] positions){
                             for (Vacancy__c p:positions){
                                           if (p.Department__c!= null) {
                                                          if (APPROVAL_MAP_CONST.containsKey(p.Department__c)){
                                                                        p.approver1__c = APPROVAL_MAP_CONST.get(p.Department__c).approver1__c;
                                                                        p.approver2__c = APPROVAL_MAP_CONST.get(p.Department__c).approver2__c;
                                                                        p.approver3__c = APPROVAL_MAP_CONST.get(p.Department__c).approver3__c;
                                                          } else {
                                                                        p.approver1__c = null;
                                                                        p.approver2__c = null;
                                                                        p.approver3__c = null;
                                                          }
                                           }
                             }
              }
}